---
deployment:
  tasks:
    # Set the deployment path on the server
    - export DEPLOYPATH=/home/hs0003173/public_html/

    # Build the project (Make sure you're using a Node.js environment on cPanel)
    - cd /home/hs0003173/my_project_directory
    - npm install
    - npm run build

    # Copy the Next.js build output to the public_html directory
    - /bin/cp -r .next/ $DEPLOYPATH/.next
    - /bin/cp -r public/ $DEPLOYPATH/public
    - /bin/cp -r out/ $DEPLOYPATH/out

    # Ensure all static files (e.g., images, CSS, JS) are copied
    - /bin/cp -r styles/ $DEPLOYPATH/styles
    - /bin/cp -r assets/ $DEPLOYPATH/assets
    - /bin/cp index.html $DEPLOYPATH

    # Run Next.js server (optional, if you're hosting with Node.js server)
    - cd $DEPLOYPATH
    - npm run start
